version: 2.1

executors:
  docker-executor:
    docker:
      - image: ghcr.io/foundry-rs/foundry:latest

jobs:
  mint-contract:
    executor: docker-executor
    parameters:
      contract-address:
        type: string
        default: "0xe1C296cb79E050EB2A52b24D9Be91f8599B32011"
      rpc-url:
        type: string
        default: "wss://optimism-sepolia-rpc.publicnode.com"
      api-url:
        type: string
        default: "http://45.146.7.38:3005/"
    steps:
      - checkout
      - run:
          name: "Install required packages"
          command: |
            apt-get update -y && apt-get install -y nodejs npm jq curl
      - run:
          name: "Validate Environment Variables"
          command: |
            for var in JWT_SECRET NAMESPACE PRIVATE_KEY; do
              if [ -z "${!var}" ]; then
                echo "Error: $var is not set!" && exit 1
              fi
            done
            echo "All required environment variables are set."
      - run:
          name: "Validate API Connection"
          command: |
            if ! curl -I "<<parameters.api-url>>unique-namespace"; then
              echo "Error: API at <<parameters.api-url>> is unreachable!" && exit 1
            fi
            echo "API endpoint is reachable."
      - run:
          name: "Prepare Logs Directory"
          command: mkdir -p logs
      - run:
          name: "Check Unique Namespace"
          command: |
            http_code=$(curl -s -o body.txt -w "%{http_code}" -X POST "<<parameters.api-url>>unique-namespace" \
              -H "Authorization: Bearer $JWT_SECRET" \
              -H "Content-Type: application/json" \
              -d '{"namespace":"'"$NAMESPACE"'"}')

            body=$(cat body.txt)

            echo "$body" >> logs/check_unique_namespace.log

            if [ "$http_code" -ne 200 ]; then
              echo "Error: HTTP status $http_code while checking namespace uniqueness. Response: $body"
              exit 1
            fi

            is_unique=$(echo "$body" | jq -r '.unique')
            if [ "$is_unique" != "true" ]; then
              echo "Error: Namespace is not unique. Response: $body"
              exit 1
            fi
            echo "Namespace is unique. Response: $body"
      - run:
          name: "Check Unique Generated Key"
          command: |
            http_code=$(curl -s -o body.txt -w "%{http_code}" -X POST "<<parameters.api-url>>unique-generated-key" \
              -H "Authorization: Bearer $JWT_SECRET" \
              -H "Content-Type: application/json" \
              -d '{"key":"'"$NAMESPACE"'"}')

            body=$(cat body.txt)

            echo "$body" >> logs/check_unique_generated_key.log

            if [ "$http_code" -ne 200 ]; then
              echo "Error: HTTP status $http_code while checking generated key uniqueness. Response: $body"
              exit 1
            fi

            is_unique=$(echo "$body" | jq -r '.unique')
            if [ "$is_unique" != "true" ]; then
              echo "Error: Generated key is not unique. Response: $body"
              exit 1
            fi
            echo "Generated key is unique. Response: $body"
      - run:
          name: "Mint Namespace Token and Save Logs"
          command: |
            cast send <<parameters.contract-address>> "safeMint(string)" "$NAMESPACE" \
              --rpc-url <<parameters.rpc-url>> \
              --private-key "$PRIVATE_KEY" | tee logs/mint_result.log
      - run:
          name: "Parse and Check Mint Result"
          command: |
            status=$(grep "status" logs/mint_result.log | awk '{print $2}')
            tx_hash=$(grep "transactionHash" logs/mint_result.log | awk '{print $2}')
            
            if [ "$status" -eq 1 ] && [ -n "$tx_hash" ]; then
              echo "Minting succeeded!"
            else
              echo "Minting failed. Check logs/mint_result.log for details." && exit 1
            fi
      - run:
          name: "Generate Key Pair"
          command: |
            http_code=$(curl -s -o body.txt -w "%{http_code}" -X POST "<<parameters.api-url>>api/v0/key/gen?arg=$NAMESPACE&type=rsa" \
              -H "Authorization: Bearer $JWT_SECRET" \
              -H "Content-Type: application/json")

            body=$(cat body.txt)

            echo "$body" >> logs/generate_key_pair.log

            if [ "$http_code" -ne 200 ]; then
              echo "Error: Failed to generate a new key pair. HTTP status $http_code. Response: $body"
              exit 1
            fi

            echo "Key pair generated successfully. Response: $body"

      - run:
          name: "Generate CAR File"
          command: |
            npm install
            node generateCarBlob.js

      - run:
          name: "Import CAR File via DAG Import"
          command: |
            car_file=$(find car_files -type f -name "*.car")
            if [ -z "$car_file" ]; then
              echo "Error: CAR file not found!" && exit 1
            fi
            
            http_code=$(curl -s -o body.txt -w "%{http_code}" -X POST "<<parameters.api-url>>api/v0/dag/import?pin-roots=true" \
              -H "Authorization: Bearer $JWT_SECRET" \
              -F "file=@${car_file}")
            
            body=$(cat body.txt)
            
            echo "$body" >> logs/dag_import.log

            if [ "$http_code" -ne 200 ]; then
              echo "Error: Failed to import CAR file. HTTP status $http_code. Response: $body"
              exit 1
            fi
            
            echo "CAR file imported successfully. Response: $body"

      - store_artifacts:
          path: logs/check_unique_namespace.log
          destination: unique-namespace-log
      - store_artifacts:
          path: logs/check_unique_generated_key.log
          destination: unique-generated-key-log
      - store_artifacts:
          path: logs/mint_result.log
          destination: mint-result-log
      - store_artifacts:
          path: logs/generate_key_pair.log
          destination: generate-key-pair-log
      - store_artifacts:
          path: logs/dag_import.log
          destination: dag-import-log

workflows:
  main-workflow:
    jobs:
      - mint-contract